### ISSUE TITLE
Setup Neko Project Knowledge Base

### ISSUE THREAD

**Issue by atharva-tendle** [ManifoldRG/NEKO_Archive#18]
Go over the Multimodal Learning for Transformers survey.
Look into other papers and start documenting.

The idea is to have a list of papers with the following takeaways:
- Summary of the work.
- Key insights or takeaways.
- Any implementation details that might be relevant to NEKO.

We can start with key papers and then slowly build this out.

**Comment by atharva-tendle** [comment]
@harshsikka @ayushm-agrawal We can set this up over this week. I can do the initial setup and create placeholders and then people can read papers and update them as time goes on. 

I will be starting with the survey paper I shared for two reasons:
- It will/should list out all datasets that have been used for multimodal transformers.
- It will link us to major papers/works.

**Comment by harshsikka** [comment]
sgtm. as you've captured, it would be good for this to start us on the journey to basic (can be minimal, but should be thorough) knowledge management for this project and across Manifold

**Comment by harshsikka** [comment]
todo: get async update from @atharva-tendle around survey status for team, here or on discord

**Comment by harshsikka** [comment]
@atharva-tendle @ayushm-agrawal what is the status on this? if blocked, who can unblock, or if bandwidth is limited what can someone step in and help parallelize?

**Comment by bhavul** [comment]
Working on reviewing this; Partial update from what I've noticed so far:

- Seems to be useful to give a collection of architectural choices used for different kinds of modalities, however these are presented without any ablation studies or comparison between them 
- Can be most useful for datasets it talks about
- Seems to also lack many details such as not much presented on sparse or more efficient attention mechanisms. I suspect it is not exhaustive and rather cherry picked

**Comment by bhavul** [comment]
I've added a new repo for this : https://github.com/ManifoldRG/Neko-KB

Currently contains the following:
- Learnings from the survey paper
- Details of how to encode multiple modalities 
- Details of different self-attention variants 
- Mentions of different pretraining tasks
- Names of different multimodal datasets

Also created a few issues, which are basically things that remain unanswered in the survey, OR are just plainly referred to in the survey but not yet studied.

**Comment by bhavul** [comment]
Closing it now @harshsikka , feel free to re-open if you feel we need to do more before closing this.
