### ISSUE TITLE
Scope Training Costs for NEKO

### ISSUE THREAD

**Issue by harshsikka** [ManifoldRG/NEKO_Archive#3]
Based on ManifoldRG/NEKO_Archive#1 and ManifoldRG/NEKO_Archive#2, we can now likely start estimating the training cost of a GATO scale model, using a cost estimation framework like that presented in https://blog.eleuther.ai/transformer-math/

**Comment by atharva-tendle** [comment]
This one is tricky are we measuring our worst-case cost here? 
What I mean by that is the cost required to train on the whole multimodal benchmark or the cumulative cost of running various experiments on smaller subsets and varying model sizes and setups.

**Comment by harshsikka** [comment]
We can figure out how to do this later, but I imagine worst case and average case for most of the experiments we do. Part of this is investigating what we can understand before hand. Not a lot of us have large model training expertise, so this is likely several tasks. 

TODO: break this down into more atomic tasks

**Comment by bhavul** [comment]
Some more things that can be considered besides above points. 

- [ ] Cost for running training code test (let's say we add a new pre-training strategy, or modify architecture or training methodologies, whatever it costs to verify that the training works fine). 
- [ ] Possible number of parallel experiments on different datasets, and possible number of iterations required on collective dataset
- [ ] Some numbers from mosaicML may be useful too (https://www.mosaicml.com/blog/gpt-3-quality-for-500k) to get a sense of costs if resources are utilized effectively

I also suspect that unless we use a service like MosaicML, there may be node failures and many other issues such as outlined in [OPT paper](https://arxiv.org/pdf/2205.01068.pdf) which would have to be taken care of. Some amount may get spent in making sure our Infra and MLOps around training is robust.

**Comment by BobakBagheri** [comment]
Closing Issue, precursor information to work being done in ManifoldRG/NEKO#40 
following actions will be documented in 28.
