### ISSUE TITLE
Language Dataset Proposals

### ISSUE THREAD

**Issue by atharva-tendle** [ManifoldRG/NEKO_Archive#6]
**Goal:**

We want to look into the language datasets used in the GATO paper as a starting point and survey for information related to those.
Ideally, we would like to know the following pieces of information for each dataset:
- Is it open source?
- Does it have proper licensing?
- Can we easily use it for training (code availability etc.)

More items can be added to the list above but these are just some rough ideas.

**Output:** 

- Update the dataset Google sheet with the above information. 
- For the datasets that are not easily accessible, we might want to research alternatives and do that in a systematic fashion by understanding the desirable characteristics of a replacement.

**Comment by harshsikka** [comment]
Excellent. As you figure out new potential dataset investigation tasks (i.e we want to to capture this kind of data - someone needs to find it), feel free to add them as their own atomic issues.

**Comment by atharva-tendle** [comment]
There is a singular only-text dataset that was used and it is not publicly available and therefore can be dealt with at a later stage. Will add the recommendation and plan to #5

**Comment by atharva-tendle** [comment]
Closing Issue. Created scoped-out follow-up issues in the backlog.
